@url=http://localhost:3001
@json=Content-Type: application/json
###
get {{url}}

### 注册
post {{url}}/register
{{json}}

{
  "name": "xj1",
  "password": "123",
  "resigerTime": "Mon Sep 07 2020 11:46:31 GMT+0800",
  "avator": "4.jpg",
  "email": "xiaojia@qq.com"
}
### 登录
post {{url}}/login
{{json}}

{
  "name":"xj",
  "password":"123"
}

### 获取帖子
get {{url}}/posts/3
{{json}}

### 增加帖子
post {{url}}/posts/3
{{json}}

{
  "userId":2,
  "title":"你好，明天",
  "content": "今天是个好日子\n今天是个好日子\n今天是个好日子\n今天是个好日子\n今天是个好日子\n今天是个好日子\n"
}

### 获得回复
get {{url}}/comments/1

### 增加回复
post {{url}}/comments/1
{{json}}

{
  "content": "hi,33"
}
